### PR TITLE
add runtime virtual machine limits

### PR DESCRIPTION
**Pull request by amgando**
addressing request for docs in https://github.com/nearprotocol/nearcore/issues/1692

### CODE REVIEW

**Comment by amgando** [comment]
@nearmax and @evgenykuzyakov -- please take a look

- is this enough?  i didn't create anything new really, just copy pasta from the source and a sentence to contextualize.
- is this in a sensible location?  it's under API

**Comment by nearmax** [comment]
Should be exhaustive, if we find something that we missed we will file an issue. Also, as of https://github.com/nearprotocol/NEPs/pull/32 nomicon.io lives in NEPs repo and contains standards and specs only. This documentation here is mostly spec so we should put it there (but first strip it of the Rust-specific code, e.g. use pseudocode).

**Comment by evgenykuzyakov** [comment]
> is this in a sensible location? it's under API

Better to go under smart contracts section, because it affects smart contracts limits

**Comment by amgando** [comment]
@evgenykuzyakov 
> _Better to go under smart contracts section, because it affects smart contracts limits_

this has been moved to `Developer/Smart Contracts` section of the docs

@nearmax 
> _put this content into NEP for nomicon.io_

created this issue.  not sure what the format of the new NEP / specs PR should be in this case.  can you help direct me?

see here: https://github.com/nearprotocol/NEPs/issues/36

**Pull request merged**
